# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'skybonds' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Charts'
  pod 'PromiseKit'
  pod 'Alamofire'

  # Pods for skybonds

  target 'skybondsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'skybondsUITests' do
    # Pods for testing
  end

end
